# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  USE_DEBUG: '{{if eq .DEBUG "1"}}-debug{{else}}{{end}}'
  USE_TRACY: true
  DLL_EXT: '{{if eq OS "windows"}}dll{{else}}so{{end}}'
  EXE_EXT: '{{exeExt | default ".bin"}}'

tasks:

  test:
    cmds:
      - echo {{.USE_DEBUG}} {{.DLL_EXT}} {{.EXE_EXT}}

  build:
    cmds:
      - |
        odin build src -build-mode:shared -define:VALIDATION=true \
        -out:bin/app.{{.DLL_EXT}} -show-timings -o:none -use-separate-modules \
        -collection:packages=packages -define:GLFW_SHARED=true \
        -define:TRACY_ENABLE={{.USE_TRACY}} {{.USE_DEBUG}}
    sources:
      - src/**/*.odin
      - window/**/*.odin
      - monitor/**.*.odin
    generates:
      - bin/app.dll

  build-shaders:
    aliases: [a2]
    cmds:
      - glslc -fshader-stage=frag assets/shaders/Builtin.Object.frag.glsl -o bin/assets/shaders/Builtin.Object.frag.spv --target-env=vulkan
      - glslc -fshader-stage=vert assets/shaders/Builtin.Object.vert.glsl -o bin/assets/shaders/Builtin.Object.vert.spv --target-env=vulkan
      - spirv-link bin/assets/shaders/Builtin.Object.frag.spv bin/assets/shaders/Builtin.Object.vert.spv -o bin/assets/shaders/Builtin.Object.spv

      - glslc -fshader-stage=frag assets/shaders/Builtin.Cubemap.frag.glsl -o bin/assets/shaders/Builtin.Cubemap.frag.spv
      - glslc -fshader-stage=vert assets/shaders/Builtin.Cubemap.vert.glsl -o bin/assets/shaders/Builtin.Cubemap.vert.spv 
      - spirv-link bin/assets/shaders/Builtin.Cubemap.frag.spv bin/assets/shaders/Builtin.Cubemap.vert.spv -o bin/assets/shaders/Builtin.Cubemap.spv

      - glslc -fshader-stage=frag assets/shaders/Builtin.ShadowPass.frag.glsl -o bin/assets/shaders/Builtin.ShadowPass.frag.spv
      - glslc -fshader-stage=vert assets/shaders/Builtin.ShadowPass.vert.glsl -o bin/assets/shaders/Builtin.ShadowPass.vert.spv 
      - spirv-link bin/assets/shaders/Builtin.ShadowPass.frag.spv bin/assets/shaders/Builtin.ShadowPass.vert.spv -o bin/assets/shaders/Builtin.ShadowPass.spv
    sources:
      - assets/shaders/**/*.glsl
    generates:
      - bin/assets/shaders/Builtin.Object.spv
      - bin/assets/shaders/Builtin.Cubemap.spv

  build-loader:
    cmds:
      - |
        odin build loader -use-separate-modules -collection:packages=packages \
        -o:none -define:FLOATING=false -define:GLFW_SHARED=true {{.USE_DEBUG}} -define:TRACY_ENABLE={{.USE_TRACY}} -out:loader{{.EXE_EXT}}
    sources:
      - loader/**/*.odin
      - window/**/*.odin
      - monitor/**.*.odin
    generates:
      - loader{{.EXE_EXT}}

  release:
    deps: [build-shaders]
    cmds:
      - |
        odin build src -build-mode:exe -define:VALIDATION=false \
        -out:bin/app{{exeExt}} -show-timings -o:speed -use-separate-modules \
        -collection:packages=packages -define:GLFW_SHARED=false \
        -define:TRACY_ENABLE={{.USE_TRACY}} -define:RELEASE=true
      
  run:
    deps: [build-loader, build, build-shaders]
    cmds:
      - ./loader{{.EXE_EXT}}

  debugger:
    platforms: [windows]
    deps: [build-loader, build, build-shaders]
    cmds:
      - raddbg.exe --profile:vulkan_test.raddbgprofile
